### ISSUE TITLE
[Seeking opinion] Rename `complete_redcap_username()` ?

### ISSUE THREAD

**Issue by cathblatter** [INS-Basel/instools#20]
- `fill_redcap_users()`?
- `complete_redcap_csv()`?

or introduce all redcap-functions with a prefix:

- `redcap_fill_users()`?

other issue: 
add argument to pass filename manually

**Comment by cathblatter** [comment]
open for opinions... @srhholzer

**Comment by srhholzer** [comment]
@cathblatter I like the version `redcap_fill_users()` with the prefix. I would avoid the version that contains the word "complete" as you never know what it really is complete.
For the "other issue": what do you mean by _pass file name manually_?

**Comment by cathblatter** [comment]
technically this would imply two things:

- stale or better alias the function `complete_redcap_username()`
- probably alias versions such as _fill_user(), _fill_usernames()...

I think - to avoid confusion - it should be _username() as this is the notation of the column?

would you like to start a PR with this to mark your first contribution to instools? 😃

**Comment by cathblatter** [comment]
the function currently reads the file name by default from a folder, see here: 
[https://github.com/INS-Basel/instools/blob/f3520c8a9f39c857abefc57246c0c84d13807ada/R/complete_redcap_username.R#L19)](https://github.com/INS-Basel/instools/blob/main/R/complete_redcap_username.R#L19)

actually looking at the code again I see that I made mistake in thinking - the argument which_file can also take an input file... but the documentation needs definitely an upkeep IMHO 🙈

**Comment by cathblatter** [comment]
closed by #21
